### ISSUE TITLE
Current causes `ember new --yarn` to fail

### ISSUE THREAD

**Issue by chriskrycho** [notion-cli/notion#346] opened 2019-04-12 00:12 UTC
The `ember new` command runs `yarn` (and a number of other tools in the JS ecosystem do likewise). The output is:

```
Yarn could not be found.
```

I'll see if I can identify where in the pipeline this is falling down; my guess is that Ember CLI making some assumptions about where it can find `yarn` that aren't holding, but it may be that we're failing to pass through the right way.

cc. @rwjblue who has a fair bit of experience with both Notion and Ember CLI.

**Comment by charlespierce** [comment] 2019-04-12 00:23
Yeah, this is caused by #325, essentially the virtual environment that `ember` is run in never has yarn available, so we want to merge with the user platform to get the default yarn version they have installed.

Addressed in #332 (and `ember new --yarn` was actually the test case I used)

**Comment by chriskrycho** [comment] 2019-04-12 00:24
Ah, makes sense. I'll review that next, then!

**Closed** 2019-04-12 00:24 UTC
