### ISSUE TITLE
which node

### ISSUE THREAD

**Issue by HazAT** [notion-cli/notion#307] opened 2019-03-11 10:25 UTC
This is more of a feature request and I hope I didn't miss this in the documentation.

I am moving over from `nvm` and really like `notion`.
One feature I am missing though is a equivalent of `nvm which node`.

Reason being if you are running a react-native application, Xcode tries to call `node` directly from 
`/usr/local/bin/node` which doesn't exist.

Same thing happens in `nvm` but with `nvm` I am able to locate the actual node binary that is used.
This seems to be super tricky in notion.
What do you have to do to make this work or to work around this?

I know the binary is located in
```bash
$HOME/.notion/bin/node
```

But it has not the actual node version in the path like in nvm.

**Comment by charlespierce** [comment] 2019-03-11 17:08
Hi @HazAT! Thanks for the suggestion! This is actually a duplicate of #167, and there is an open PR #293 to add a `notion which` command to do exactly that, so it should be coming shortly.

**Closed by charlespierce** 2019-03-11 17:08 UTC

**Comment by HazAT** [comment] 2019-03-12 14:30
Doh! 
Thanks and sorry for not using the search 🙈
